Repository GitHawkApp/GitHawk, pull requests merged in 2018-12, with the labels that each got.

#2521 Readme update-2
  README.md
Labels: ready-to-pull

#2524 New inbox header to select inbox type (all, mentioned, repo, etc)
  Classes/Notifications/Filter/GithubClient+InboxFilterController.swift
  Classes/Notifications/Filter/InboxFilterController.swift
  Classes/Notifications/Filter/InboxFilterModel.swift
  Classes/Notifications/Filter/InboxFilterRepoCell.swift
  Classes/Notifications/Filter/InboxFilterRepoSectionController.swift
  Classes/Notifications/Filter/InboxFilterReposViewController.swift
  Classes/Notifications/InboxDashboardCell.swift
  Classes/Notifications/InboxDashboardModel.swift
  Classes/Notifications/InboxDashboardSectionController.swift
  Classes/Notifications/InboxType.swift
  Classes/Notifications/NotificationCell.swift
  Classes/Notifications/NotificationModelController.swift
  Classes/Notifications/NotificationsViewController.swift
  Classes/Systems/Announcer.swift
  Classes/View Controllers/ContrastContextMenu.swift
  Classes/View Controllers/RootViewControllers.swift
  Classes/Views/Styles.swift
  Freetime.xcodeproj/project.pbxproj
  Local Pods/GitHubAPI/GitHubAPI.xcodeproj/project.pbxproj
  Local Pods/GitHubAPI/GitHubAPI/V3Issue.swift
  Local Pods/GitHubAPI/GitHubAPI/V3IssuesRequest.swift
  Local Pods/GitHubAPI/GitHubAPI/V3SubscriptionsRequest.swift
  Podfile.lock
  Pods/ContextMenu/ContextMenu/CGRect+DominantCorner.swift
  Pods/ContextMenu/ContextMenu/ClippedContainerViewController.swift
  Pods/ContextMenu/ContextMenu/ContextMenu+Options.swift
  Pods/ContextMenu/ContextMenu/ContextMenu+Position.swift
  Pods/ContextMenu/ContextMenu/ContextMenu.swift
  Pods/ContextMenu/ContextMenu/ContextMenuPresentationController.swift
  Pods/ContextMenu/ContextMenu/SourceViewCorner.swift
  Pods/Local Podspecs/ContextMenu.podspec.json
  Pods/Manifest.lock
  Pods/Pods.xcodeproj/project.pbxproj
  Pods/Target Support Files/ContextMenu/Info.plist
  Settings.bundle/com.mono0926.LicensePlist.plist
Labels: WIP

#2532 remove "remove bookmarks" part of the signout message
  Classes/Settings/SettingsViewController.swift
Labels: awaiting-review, trivial

#2525 Add forks to search
  Classes/Search/SearchViewController.swift
Labels: awaiting-review

#2538 Open external links in Safari
  Classes/Settings/Defaults+ExternalLinks.swift
  Classes/Settings/Settings.storyboard
  Classes/Settings/SettingsViewController.swift
  Classes/View Controllers/UIViewController+Safari.swift
  Freetime.xcodeproj/project.pbxproj
Labels: awaiting-review
