Repository GitHawkApp/GitHawk, pull requests merged in 2019-03, with the labels that each got.

#2611 Dismiss spinner only after code view is rendered
  Classes/Repository/RepositoryCodeBlobViewController.swift
  Classes/Views/CodeView.swift
Labels: awaiting-review

#2547 switch from the now deprecated to the new status page
  Classes/Settings/SettingsViewController.swift
  Classes/Views/Styles.swift
  Local Pods/GitHubAPI/GitHubAPI/GitHubAPIStatusRequest.swift
Labels: awaiting-changes

#2683 Fix for "Accessibility “bullets hollow” should be “more options” #2673
  Classes/Repository/RepositoryCodeBlobViewController.swift
  Classes/Repository/RepositoryCodeDirectoryViewController.swift
  Classes/Repository/RepositoryImageViewController.swift
Labels: awaiting-review, trivial

#2684 Update Setup.md
  Setup.md
Labels: awaiting-review, trivial

#2690 Add haptics for merge results
  Classes/Issues/Merge/GithubClient+Merge.swift
  Classes/Issues/Merge/IssueMergeSectionController.swift
Labels: ready-to-pull, trivial

#2620 Pagination for repo branches list
  Classes/Repository/RepositoryBranches/GitHubClient+RepositoryBranches.swift
  Classes/Repository/RepositoryBranches/RepositoryBranchesViewController.swift
  gql/API.swift
  gql/RepoBranches.graphql
Labels: ready-to-pull
